Plain javascript
m05e5/awsome-books pull request #1
Opened 2021-07-05 17:25 UTC by m05e5

- Create a collection that keeps a list of books
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection
- Display all books saved in the collection in the top part of the page.

2021-07-05 22:37 UTC, Davidosky007 requested changes
Hi @mugberto @m05e5, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
* Kindly check below in the comments section and make the necessary changes 👍 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-05 22:37 UTC, Davidosky007 commented on script.js
> +}
* The collection for storing a list of the created books is missing, please fix it as currently, books created are not stored

2021-07-05 22:37 UTC, Davidosky007 commented on script.js
> +
* The function addBooks is not adding books to a collection of books eg( An array) 
* i suggest you make this function add a book to a collection and not add books directly to the DOM

2021-07-05 22:37 UTC, Davidosky007 commented on script.js
> +}
* currently books created and removed does not reflect in local storage kindly fix it 🙏

2021-07-05 22:37 UTC, Davidosky007 commented on script.js
> +});
* When the add button is clicked this error shows up please fix it 🙏 
![Screenshot (144)](https://user-images.githubusercontent.com/52497246/124521973-606ff300-dde9-11eb-9083-23207c91a14f.png)

2021-07-06 08:56 UTC, mimipeshy approved these changes
## Hi Team @m05e5 and @mugberto 👋🏾 👋🏾 , 

Your project is complete! 
#### Highlights

- You have made the changes requested by the previous TSE ✔️ 

 There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 08:58 UTC, merged